language: java
sudo: false
install:
    ant_library "ant-contrib" do
        url "http://search.maven.org/remotecontent?filepath=ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar"
    end
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8